# Generated by Django 5.1.2 on 2024-10-28 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka_name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.TextField()),
                ('price', models.PositiveSmallIntegerField(default=0)),
                ('color', models.CharField(max_length=10)),
                ('volume', models.PositiveSmallIntegerField(default=0)),
                ('year', models.IntegerField()),
                ('type_change', models.BooleanField()),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.marka')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=16, null=True)),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.marka')),
            ],
        ),
    ]
