# Generated by Django 5.1.2 on 2024-10-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_car_description_en_car_description_ky_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='title',
        ),
        migrations.RemoveField(
            model_name='car',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='car',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='car',
            name='title_ru',
        ),
        migrations.AddField(
            model_name='car',
            name='title_name',
            field=models.CharField(default=2, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='title_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='title_name_ky',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='title_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
